#自定义端口
server:
  port: 8702
#eureka注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka/ #其实就是：http://localhost:8700/
  instance:
    hostname: localhost


spring:
  application:
    name: user-service #web应用服务名称


#日志配置
logging:
  config: classpath:logback.xml